### ISSUE TITLE
libsecp256k1.ecssa_verify_ failed

### ISSUE THREAD

**Issue by deletelibrary** [btclib-org/btclib#124]
sig_hash_0 = sig_hash.from_tx(prevouts, tx, i, sig_hash.ALL)
    sig = ssa.sign(sig_hash_0,wallet['private_key'])
    pub_key = type_and_payload(prevouts[i].script_pub_key.script)[1]
    ssa.assert_as_valid_(sig_hash_0,pub_key,sig)

err
Traceback (most recent call last):
  File "C:\Users\27852\Desktop\pow\pow-20\wallet\test_tx\taproot.py", line 57, in <module>
    ssa.assert_as_valid_(sig_hash_0,pub_key,sig)
  File "C:\Users\27852\AppData\Local\Programs\Python\Python312\Lib\site-packages\btclib\ecc\ssa.py", line 300, in assert_as_valid_
    raise BTClibRuntimeError("libsecp256k1.ecssa_verify_ failed")
btclib.exceptions.BTClibRuntimeError: libsecp256k1.ecssa_verify_ failed

**Comment by fametrano** [comment]
Reproduced, and it is a usage problem with two independent causes — both in the four lines you posted, neither in the bindings.

**1. `sign` and `assert_as_valid_` are not a pair.** btclib’s trailing
underscore says who hashes: `ssa.sign(msg, ...)` reduces its argument
with `hf` first and signs `sha256(msg)`, while `ssa.assert_as_valid_(msg,
...)` takes the BIP340 message **as it is**. Your code signs
`sha256(sig_hash_0)` and verifies `sig_hash_0`, so the two are about
different messages. Use `ssa.sign_` — and for a real spend it has to be
that one, because BIP341 signs the sighash itself; the `sign` +
`assert_as_valid` pairing verifies against itself but produces a
signature no consensus rule accepts.

**2. The key from the script is the *tweaked* key.**
`type_and_payload(prevouts[i].script_pub_key.script)[1]` is the 32-byte
taproot **output** key, `Q = P + t·G`, not your internal key. A key path
spend signs with the tweaked private key:
`btclib.script.taproot.output_prvkey(prv_key, script_tree)`.

Measured on `dev`, one variable at a time — a p2tr prevout, its spending
tx, `sig_hash.from_tx(prevouts, tx, 0, sig_hash.ALL)`:

| signing call | key | result |
| --- | --- | --- |
| `ssa.sign` | internal | `signature verification failed` (your case) |
| `ssa.sign_` | internal | `signature verification failed` |
| `ssa.sign` | `output_prvkey` | `signature verification failed` |
| `ssa.sign_` | `output_prvkey` | **verified** |

So:

```python
from btclib.script.taproot import output_prvkey

sig_hash_0 = sig_hash.from_tx(prevouts, tx, i, sig_hash.ALL)
sig = ssa.sign_(sig_hash_0, output_prvkey(wallet["private_key"]))
pub_key = type_and_payload(prevouts[i].script_pub_key.script)[1]
ssa.assert_as_valid_(sig_hash_0, pub_key, sig)   # passes
```

Pass the same `script_tree` to `output_prvkey` that built the address, if
there is one.

Two related notes.

- `sig_hash.ALL` (`0x01`) and SIGHASH_DEFAULT (`0x00`) give **different**
  sighashes, the hash type being in the BIP341 preimage. With `ALL` the
  witness signature must be 65 bytes, that byte appended; with the
  default it is 64 and nothing is appended. btclib refused to *carry* the
  65-byte form in a psbt until #122, fixed today.
- the message you saw is gone: `assert_as_valid_` now raises `signature
  verification failed` whichever implementation ran, instead of naming
  the internal helper — telling a caller which backend was used rather
  than what went wrong was the defect in the report, and it is fixed on
  `dev`.

Closing as answered. Note that btclib has no Signer role: it signs and
verifies, and building the witness for the spend is yours to do.
